begin;
select plan(9);
select has_table('public', 'vault_device_authorizations', 'device authorization ledger exists');
select has_table('public', 'vault_account_operations', 'account operation ledger exists');
select has_table('public', 'vault_recovery_epoch_envelopes', 'recovery envelope table exists');
select col_not_null('public', 'vault_device_authorizations', 'signature', 'device authorizations require a signature');
select col_not_null('public', 'vault_device_authorizations', 'proof_of_possession_signature', 'device authorizations retain the device possession signature');
select col_not_null('public', 'vault_account_operations', 'operation_hash', 'account operations are hash-linked');
select ok((select relrowsecurity from pg_class where oid = 'public.vault_device_authorizations'::regclass), 'device authorization rows use RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.vault_account_operations'::regclass), 'account operation rows use RLS');
select ok(not has_table_privilege('authenticated', 'public.vault_account_operations', 'insert'), 'browser cannot append trust operations directly');
select * from finish();
rollback;
