import type { Metadata } from 'next';
import { ArrowUpRight, Braces, GitBranch, PackageCheck, ServerOff, ShieldCheck } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { FeatureCard, PageIntro } from '@/components/marketing/Marketing';
import { documentationConfig, siteConfig } from '@/config/site';
import type { Locale } from '@/i18n/config';
export const metadata:Metadata={title:'Developers',description:'Build and contribute to the programmable ClipsX clipboard.'};
const d={en:{intro:['Developers','Build at the clipboard boundary.','ClipsX exposes a reviewed extension contract today. Hosted and public APIs are planned, and are not part of the current release.'],cards:[['Extension contract','Create bounded WASM packages that contribute detection, transforms, views, and actions.'],['Package CLI','Validate manifests and packages against the same contract enforced by the desktop host.'],['Conformance first','Tests keep package behavior portable and make capability boundaries reviewable.'],['Signed publishing','The registry signs exact immutable releases and supports recovery and revocation.'],['Security model','The host owns consent, limits, rendering, accessibility, and local secrets.'],['Public API: planned','Do not build against an undocumented hosted API. Follow the roadmap and contribute use cases.']],github:'Explore the source',docs:'Read developer docs'},ja:{intro:['開発者向け','クリップボードの境界で作る。','現在は審査済みの拡張契約を公開しています。ホスト型・公開 API は計画段階で、現行リリースには含まれません。'],cards:[['拡張契約','検出、変換、表示、操作を追加する制限付き WASM パッケージを作れます。'],['パッケージ CLI','デスクトップホストと同じ契約に対してマニフェストとパッケージを検証します。'],['適合性を優先','テストが移植性を保ち、権限境界を審査可能にします。'],['署名付き公開','レジストリは不変のリリースを署名し、復旧と失効に対応します。'],['セキュリティモデル','同意、制限、表示、アクセシビリティ、秘密情報はホストが管理します。'],['公開 API：計画中','未文書化のホスト API に依存せず、ロードマップへユースケースを共有してください。']],github:'ソースを見る',docs:'開発者ドキュメント'}} as const;
export default async function Developers({params}:{params:Promise<{locale:Locale}>}){const {locale}=await params;setRequestLocale(locale);const c=d[locale];const icons=[Braces,GitBranch,PackageCheck,ShieldCheck,ShieldCheck,ServerOff];return <div className="marketing-shell pb-24"><PageIntro eyebrow={c.intro[0]} title={c.intro[1]} description={c.intro[2]}/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{c.cards.map((card,i)=><FeatureCard key={card[0]} icon={icons[i]} title={card[0]}>{card[1]}</FeatureCard>)}</div><div className="mt-10 flex flex-wrap justify-center gap-3"><a href={siteConfig.repository} target="_blank" rel="noreferrer" className="button-primary px-5 py-3">{c.github}<ArrowUpRight className="ml-2" size={16}/></a><a href={documentationConfig.root} target="_blank" rel="noreferrer" className="button-secondary px-5 py-3">{c.docs}</a></div></div>}
