'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { useTranslations } from 'next-intl';
import { ChevronDown, CreditCard, GitBranch as Github, LogOut, Menu, UserRound, X } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { Link, useRouter } from '@/i18n/routing';
import { mainNav } from '@/config/nav';
import { siteConfig } from '@/config/site';
import { createClient } from '@/lib/supabase/client';
import { LocaleSwitcher } from './LocaleSwitcher';
import { getUserAvatar, getUserInitials } from './header-profile';

export function Header({ user }: { user: User | null }) {
  const t = useTranslations(); const router = useRouter();
  const [mobileOpen, setMobileOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const [loading, setLoading] = useState(false);
  const accountRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!accountRef.current?.contains(event.target as Node)) setAccountOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  async function signOut() { setLoading(true); await createClient().auth.signOut(); setAccountOpen(false); router.push('/'); router.refresh(); }
  const avatar = user ? getUserAvatar(user) : null; const initials = user ? getUserInitials(user) : null;
  const accountControl = user ? <div className="relative" ref={accountRef}><button type="button" aria-label={t('Nav.account')} aria-haspopup="menu" aria-expanded={accountOpen} onClick={() => setAccountOpen(!accountOpen)} className="focus-ring flex items-center gap-1 rounded-full border border-black/10 bg-white p-1 pr-2 text-slate-600 shadow-sm transition hover:border-violet-400/60 dark:border-white/10 dark:bg-slate-900 dark:text-slate-300"><span className="flex h-8 w-8 items-center justify-center overflow-hidden rounded-full bg-slate-900 text-xs font-bold text-white dark:bg-violet-400 dark:text-slate-950">{avatar ? <Image src={avatar} alt="" width={32} height={32} unoptimized /> : initials ?? <UserRound size={16}/>}</span><ChevronDown size={14}/></button>{accountOpen && <div role="menu" className="absolute right-0 mt-2 w-56 rounded-xl border border-black/10 bg-white p-2 shadow-xl dark:border-white/10 dark:bg-slate-950"><p className="truncate px-3 py-2 text-xs text-slate-500">{user.email}</p><Link role="menuitem" href="/account" onClick={() => setAccountOpen(false)} className="menu-item"><UserRound size={15}/>{t('Nav.account')}</Link><Link role="menuitem" href="/account/billing" onClick={() => setAccountOpen(false)} className="menu-item"><CreditCard size={15}/>{t('Nav.billing')}</Link><button role="menuitem" type="button" onClick={signOut} disabled={loading} className="menu-item w-full"><LogOut size={15}/>{loading ? t('Nav.signingOut') : t('Nav.signOut')}</button></div>}</div> : <Link href="/signin" aria-label={t('Nav.signIn')} title={t('Nav.signIn')} className="icon-button"><UserRound size={18}/></Link>;
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-black/5 bg-[rgba(248,250,252,.86)] backdrop-blur-xl dark:border-white/5 dark:bg-[rgba(2,6,23,.86)]"><div className="mx-auto flex h-16 max-w-[1440px] items-center px-4 sm:px-6 lg:px-8"><Link href="/" className="focus-ring flex items-center gap-2.5 rounded-md" aria-label="ClipsX home"><Image src="/icons/monochromatic.svg" alt="" width={34} height={34} priority/><span className="font-heading text-sm font-bold tracking-[.2em]">CLIPS<span className="text-slate-400">X</span></span></Link><nav aria-label="Primary" className="ml-10 hidden items-center gap-0.5 xl:flex">{mainNav.map((item) => <Link key={item.href} href={item.href} className="nav-link">{t(item.labelKey as never)}</Link>)}</nav><div className="ml-auto hidden items-center gap-2 xl:flex"><LocaleSwitcher/><a href={siteConfig.repository} target="_blank" rel="noreferrer" className="icon-button" aria-label={t('Nav.github')} title={t('Nav.github')}><Github size={18}/></a>{accountControl}<Link href="/download" className="button-primary ml-1 px-4 py-2 text-sm">{t('Nav.download')}</Link></div><button type="button" onClick={() => setMobileOpen(!mobileOpen)} aria-expanded={mobileOpen} aria-label={t('Nav.menu')} className="icon-button ml-auto xl:hidden">{mobileOpen ? <X size={20}/> : <Menu size={20}/>}</button></div>{mobileOpen && <div className="border-t border-black/5 bg-white p-4 xl:hidden dark:border-white/5 dark:bg-slate-950"><nav className="grid gap-1">{mainNav.map((item) => <Link key={item.href} href={item.href} onClick={() => setMobileOpen(false)} className="nav-link py-3">{t(item.labelKey as never)}</Link>)}</nav><div className="mt-3 flex items-center gap-2 border-t border-black/5 pt-4 dark:border-white/5"><LocaleSwitcher/><a href={siteConfig.repository} target="_blank" rel="noreferrer" className="icon-button" aria-label={t('Nav.github')}><Github size={18}/></a>{accountControl}<Link href="/download" className="button-primary ml-auto px-4 py-2 text-sm">{t('Nav.download')}</Link></div></div>}</header>;
}
