import type { Locale } from '@/i18n/config';

export type Localized = Record<Locale, string>;
export const pick = (value: Localized, locale: Locale) => value[locale];
export const l = (en: string, ja: string): Localized => ({ en, ja });

export const docs = [
  { slug:'getting-started', title:l('Getting started','はじめに'), summary:l('Install ClipsX, open history, and understand the first-run choices.','ClipsX の導入、履歴画面、初回設定を説明します。') },
  { slug:'workflows', title:l('Core workflows','基本ワークフロー'), summary:l('Capture, find, preview, organize, copy, paste, export, and share.','保存、検索、プレビュー、整理、コピー、貼り付け、書き出し、共有。') },
  { slug:'privacy', title:l('Privacy and data ownership','プライバシーとデータ所有'), summary:l('What remains local, what can sync, and what never leaves silently.','ローカルに残るもの、同期できるもの、無断送信されないもの。') },
  { slug:'meaning-search', title:l('Meaning Search','意味検索'), summary:l('How optional semantic retrieval works and how to rebuild its local index.','任意の意味検索とローカルインデックスの再構築。') },
  { slug:'recall', title:l('Recall','Recall'), summary:l('Ask selected history, inspect cited evidence, and understand the local generation boundary.','選択した履歴に質問し、引用された根拠とローカル生成の境界を確認します。') },
  { slug:'ollama', title:l('Ollama setup','Ollama の設定'), summary:l('Connect a loopback Ollama endpoint, select a model, and troubleshoot health.','ローカルの Ollama 接続、モデル選択、問題解決。') },
  { slug:'extensions', title:l('Extensions','拡張機能'), summary:l('Install signed packages, review permissions, and manage recovery.','署名済みパッケージの導入、権限確認、復旧管理。') },
  { slug:'developers', title:l('Developer overview','開発者概要'), summary:l('The extension contract, CLI, registry, and contribution boundaries.','拡張機能契約、CLI、レジストリ、貢献範囲。') },
  { slug:'sync', title:l('Account and settings sync','アカウントと設定同期'), summary:l('Selected settings can roam; clipboard content does not.','一部設定は同期できますが、クリップ内容は同期しません。') },
  { slug:'platforms', title:l('Platform support','対応プラットフォーム'), summary:l('Current Windows, Linux, and macOS release status and limitations.','Windows、Linux、macOS のリリース状況と制限。') },
] as const;
export type DocSlug = typeof docs[number]['slug'];
export const docBodies: Record<DocSlug, { sections: Array<{title:Localized; paragraphs:Localized[]}>; resources?: Array<{label:Localized;href:string;external?:boolean}> }> = {
  'getting-started': {sections:[{title:l('Before you install','インストール前'),paragraphs:[l('Use only a release marked available on the Download page. Windows and Linux are the first release targets; macOS remains unavailable until its distribution path is ready.','ダウンロードページで利用可能と表示されたリリースのみ使用してください。初回対象は Windows と Linux で、macOS は配布準備が整うまで利用できません。'),l('An account is optional for the core desktop product. Sign in only when you want supported settings sync or account services.','デスクトップの基本機能にアカウントは不要です。対応設定の同期やアカウント機能が必要な場合のみサインインしてください。')]},{title:l('Your first clip','最初のクリップ'),paragraphs:[l('Copy supported content normally, open ClipsX with its shortcut, search, preview the representations captured, and choose the one to paste.','通常どおり対応コンテンツをコピーし、ショートカットで ClipsX を開き、検索して保存された表現を確認し、貼り付ける形式を選びます。')]}]},
  workflows:{sections:[{title:l('A deliberate pipeline','意図的な流れ'),paragraphs:[l('ClipsX captures canonical content first. Previews, OCR, search data, and extension results are derived so they can be rebuilt without changing the original.','ClipsX はまず原本データを保存します。プレビュー、OCR、検索データ、拡張結果は派生データとして再構築できます。'),l('Pin frequent clips, add notes and tags, filter by source or type, then copy or share the supported representation you need.','頻用クリップをピン留めし、メモやタグ、ソースや種類の絞り込みを使い、必要な対応形式をコピーまたは共有します。')]}]},
  privacy:{sections:[{title:l('Local data boundary','ローカルデータ境界'),paragraphs:[l('Clipboard content, managed files, OCR, full-text indexes, semantic sidecars, provider endpoints, models, credentials, permission grants, and diagnostics remain device-local.','クリップ内容、管理ファイル、OCR、全文インデックス、意味検索データ、接続先、モデル、認証情報、権限、診断情報は端末内に残ります。'),l('ClipsX never silently downloads a model or sends clipboard content to a hosted provider. Any future hosted integration must ask for explicit consent.','モデルを無断でダウンロードしたり、クリップ内容を外部プロバイダーへ送信したりしません。将来の外部連携には明示的な同意が必要です。')]}]},
  'meaning-search':{sections:[{title:l('Optional local retrieval','任意のローカル検索'),paragraphs:[l('Meaning Search adds local embeddings and a derived semantic index. Exact identifiers continue to use lexical search, while semantic results help with concepts and half-remembered phrases.','意味検索はローカル埋め込みと派生インデックスを追加します。正確な識別子は文字検索、概念や曖昧な記憶には意味検索が役立ちます。'),l('You can disable it or delete its index without deleting clips. Ordinary clip edits update that clip’s index data; changing the embedding model builds a replacement index.','無効化やインデックス削除をしてもクリップは削除されません。通常の編集ではそのクリップの検索データを更新し、埋め込みモデルの変更時は置き換え用インデックスを構築します。')]}]},
  recall:{sections:[{title:l('Before you ask','質問する前に'),paragraphs:[l('Recall requires a configured local text-generation model. Meaning Search is optional: when embeddings are unavailable, Recall can fall back to bounded keyword-centered evidence.','Recall には設定済みのローカル文章生成モデルが必要です。意味検索は任意で、埋め込みが利用できない場合は制限されたキーワード中心の根拠にフォールバックできます。'),l('Open Recall from the built-in command or its shortcut, confirm the visible scope, enter a question, then inspect the numbered citations before using the answer.','組み込みコマンドまたはショートカットから Recall を開き、表示されている範囲を確認して質問を入力し、回答を使う前に番号付き引用を確認します。')]},{title:l('Control the evidence','根拠を選ぶ'),paragraphs:[l('Recall respects All, Favorites, Pinned, tag, representation-family, facet, and enabled-source filters. You can remove individual sources and rerun with only the clips you trust.','Recall は、すべて、お気に入り、ピン、タグ、表現形式、ファセット、有効なソースの絞り込みを尊重します。個別の根拠を外し、信頼するクリップだけで再実行できます。'),l('Detected secret clips are excluded without an override. The temporary conversation expires after inactivity, answers remain generated and fallible, and prompts or answers do not become canonical clip metadata.','検出された秘密情報のクリップは例外なく除外されます。一時的な会話は操作がないと期限切れになり、回答は生成結果として誤る可能性があります。質問や回答がクリップの原本情報になることはありません。')]}],resources:[{label:l('Explore the Recall feature','Recall の機能を見る'),href:'/recall'}]},
  ollama:{sections:[{title:l('1. Install and start Ollama','1. Ollama を導入して起動'),paragraphs:[l('Install Ollama using its official instructions for your operating system, then start the service. ClipsX does not install Ollama or download models for you.','お使いの OS 向け公式手順で Ollama を導入し、サービスを起動します。ClipsX が Ollama やモデルを自動で導入することはありません。'),l('The default local endpoint is http://localhost:11434. Keep the service on loopback: ClipsX accepts local loopback endpoints and checks provider health before saving the connection.','既定のローカル接続先は http://localhost:11434 です。サービスはループバックで使用してください。ClipsX はローカルのループバック接続を受け付け、保存前に状態を確認します。')]},{title:l('2. Connect ClipsX','2. ClipsX を接続'),paragraphs:[l('Open Intelligence, choose Models, enter the Ollama endpoint, and press Connect. ClipsX lists installed models only after the endpoint responds successfully.','Intelligence を開き、Models を選択して Ollama の接続先を入力し、Connect を押します。接続に成功すると、導入済みモデルが表示されます。'),l('For Meaning Search, select a model that Ollama reports as supporting text embeddings and press Enable. Indexing runs in the background; exact text search remains available while it builds.','意味検索には、Ollama が文章埋め込み対応として報告するモデルを選んで Enable を押します。インデックスはバックグラウンドで構築され、その間も完全一致検索を利用できます。')]},{title:l('3. Enable Recall when needed','3. 必要に応じて Recall を有効化'),paragraphs:[l('Recall uses a text-generation model, which is separate from the embedding model used by Meaning Search. Under Local Text Generation, choose an installed model that reports generation support and press Enable.','Recall は、意味検索の埋め込みモデルとは別の文章生成モデルを使用します。Local Text Generation で、文章生成対応として表示される導入済みモデルを選び、Enable を押します。'),l('Model size, speed, language quality, and memory use vary. The model capabilities discovered by ClipsX are authoritative; model names in examples are not compatibility guarantees.','モデルごとに容量、速度、言語品質、メモリ使用量が異なります。ClipsX が検出した対応機能を正とし、例にあるモデル名は互換性を保証するものではありません。')]},{title:l('Troubleshooting','問題解決'),paragraphs:[l('If the endpoint is unavailable, confirm Ollama is running and refresh the connection. If no model appears in a selector, install a model with the required embedding or generation capability, then refresh again.','接続できない場合は Ollama が起動していることを確認し、接続を更新します。選択欄にモデルが表示されない場合は、必要な埋め込みまたは文章生成機能を持つモデルを導入し、再度更新します。'),l('Changing the embedding model creates a new derived index. Clearing or rebuilding that index never deletes canonical clips. If an indexing job fails, review the diagnostic, update Ollama if needed, and retry only the failed work.','埋め込みモデルを変更すると、新しい派生インデックスを作成します。インデックスの削除や再構築で原本クリップは削除されません。処理に失敗した場合は診断を確認し、必要に応じて Ollama を更新して、失敗した処理だけを再試行します。')]}],resources:[{label:l('Official Ollama installation','Ollama 公式インストール'),href:'https://ollama.com/download',external:true},{label:l('Ollama model library','Ollama モデルライブラリ'),href:'https://ollama.com/library',external:true}]},
  extensions:{sections:[{title:l('Host-owned safety','ホストが管理する安全性'),paragraphs:[l('Extensions run as bounded WASM packages. Signed registry entries describe compatible releases; ClipsX owns capability consent, invocation limits, rendering, accessibility, and quarantine.','拡張機能は制限された WASM として動作します。署名レジストリが互換リリースを示し、権限同意、実行制限、表示、アクセシビリティ、隔離は ClipsX が管理します。'),l('Review permissions after installation and again after a package update changes its checksum. Credentials and grants never sync automatically.','導入時とチェックサムが変わる更新後に権限を確認します。認証情報と許可は自動同期されません。')]}]},
  developers:{sections:[{title:l('Build against the contract','契約に沿って構築'),paragraphs:[l('The desktop repository owns the public extension contract, package CLI, and conformance tests. First-party packages and the signed catalog live in separate repositories.','デスクトップリポジトリが公開拡張契約、パッケージ CLI、適合テストを管理します。公式パッケージと署名カタログは別リポジトリです。'),l('Public hosted APIs are planned, not available. Build current integrations as reviewed extensions rather than depending on an undocumented network API.','公開ホスト API は計画段階です。現時点では未文書化 API に依存せず、審査対象の拡張機能として構築してください。')]}]},
  sync:{sections:[{title:l('What roams','同期されるもの'),paragraphs:[l('Supported profile settings and reviewed extension or command intent can sync between signed-in devices. Local validation and fresh capability consent still apply.','対応プロファイル設定と審査済み拡張・コマンドの選択情報は端末間同期できます。各端末での検証と権限同意は必要です。'),l('Clips, notes, tags, files, archives, credentials, grants, local model endpoints, jobs, diagnostics, and derived data do not sync. Signing out preserves local data.','クリップ、メモ、タグ、ファイル、認証情報、権限、ローカルモデル接続、ジョブ、診断、派生データは同期しません。サインアウトしてもローカルデータは残ります。')]}]},
  platforms:{sections:[{title:l('Release truth','リリース状況'),paragraphs:[l('Windows x64 and Linux x64 are the first desktop release targets. An artifact is advertised only after its platform certification and publishing checks pass.','Windows x64 と Linux x64 が初回デスクトップ対象です。各プラットフォームの検証と公開チェック合格後のみ配布します。'),l('macOS builds are not a primary download until signing, hardened runtime, notarization, and stapling are complete. Linux support targets X11 for the first release.','macOS は署名、Hardened Runtime、公証、ステープル完了まで主要ダウンロードにしません。Linux 初回対応は X11 が対象です。')]}]},
};
