import type { Locale } from '@/i18n/config';

export type Localized = Record<Locale, string>;
export type ContentCard = { title: Localized; body: Localized };
export const pick = (value: Localized, locale: Locale) => value[locale];
export const l = (en: string, ja: string): Localized => ({ en, ja });

export const productCards: ContentCard[] = [
  { title:l('Keep the useful formats','有用な形式を保持'), body:l('Capture text, images, files, links, tables, rich content, and supported native representations together.','テキスト、画像、ファイル、リンク、表、リッチコンテンツ、対応するネイティブ形式をまとめて保存します。') },
  { title:l('Search exact or by meaning','完全一致と意味で検索'), body:l('Fast full-text search is always available. Optional Meaning Search uses local embeddings when you choose to configure it.','高速な全文検索を常に利用できます。任意の意味検索は、設定した場合のみローカル埋め込みを使用します。') },
  { title:l('Make images searchable','画像も検索可能に'), body:l('Platform OCR extracts useful text into rebuildable local artifacts without changing the original capture.','プラットフォームの OCR が原本を変更せず、再生成可能なローカルデータとして文字を抽出します。') },
  { title:l('Organize without friction','自然に整理'), body:l('Pin, tag, annotate, filter, and recall clips while keeping the keyboard at the center of the workflow.','ピン、タグ、メモ、フィルターを使い、キーボード中心でクリップを再発見できます。') },
  { title:l('Paste the representation you need','必要な形式で貼り付け'), body:l('ClipsX preserves supported representations and lets you deliberately copy, paste, export, or share the right one.','対応する表現を保持し、必要な形式を明示的にコピー、貼り付け、書き出し、共有できます。') },
  { title:l('Stay local by default','ローカルが既定'), body:l('Clipboard history, files, OCR, indexes, embeddings, local model settings, and secrets stay on this device.','履歴、ファイル、OCR、インデックス、埋め込み、ローカルモデル設定、秘密情報は端末内に残ります。') },
];

export const docs = [
  { slug:'getting-started', title:l('Getting started','はじめに'), summary:l('Install ClipsX, open history, and understand the first-run choices.','ClipsX の導入、履歴画面、初回設定を説明します。') },
  { slug:'workflows', title:l('Core workflows','基本ワークフロー'), summary:l('Capture, find, preview, organize, copy, paste, export, and share.','保存、検索、プレビュー、整理、コピー、貼り付け、書き出し、共有。') },
  { slug:'privacy', title:l('Privacy and data ownership','プライバシーとデータ所有'), summary:l('What remains local, what can sync, and what never leaves silently.','ローカルに残るもの、同期できるもの、無断送信されないもの。') },
  { slug:'meaning-search', title:l('Meaning Search','意味検索'), summary:l('How optional semantic retrieval works and how to rebuild its local index.','任意の意味検索とローカルインデックスの再構築。') },
  { slug:'ollama', title:l('Ollama setup','Ollama の設定'), summary:l('Connect a loopback Ollama endpoint, select a model, and troubleshoot health.','ローカルの Ollama 接続、モデル選択、問題解決。') },
  { slug:'extensions', title:l('Extensions','拡張機能'), summary:l('Install signed packages, review permissions, and manage recovery.','署名済みパッケージの導入、権限確認、復旧管理。') },
  { slug:'developers', title:l('Developer overview','開発者概要'), summary:l('The extension contract, CLI, registry, and contribution boundaries.','拡張機能契約、CLI、レジストリ、貢献範囲。') },
  { slug:'sync', title:l('Account and settings sync','アカウントと設定同期'), summary:l('Selected settings can roam; clipboard content does not.','一部設定は同期できますが、クリップ内容は同期しません。') },
  { slug:'platforms', title:l('Platform support','対応プラットフォーム'), summary:l('Current Windows, Linux, and macOS release status and limitations.','Windows、Linux、macOS のリリース状況と制限。') },
] as const;
export type DocSlug = typeof docs[number]['slug'];
export const docBodies: Record<DocSlug, { sections: Array<{title:Localized; paragraphs:Localized[]}> }> = {
  'getting-started': {sections:[{title:l('Before you install','インストール前'),paragraphs:[l('Use only a release marked available on the Download page. Windows and Linux are the first release targets; macOS remains unavailable until its distribution path is ready.','ダウンロードページで利用可能と表示されたリリースのみ使用してください。初回対象は Windows と Linux で、macOS は配布準備が整うまで利用できません。'),l('An account is optional for the core desktop product. Sign in only when you want supported settings sync or account services.','デスクトップの基本機能にアカウントは不要です。対応設定の同期やアカウント機能が必要な場合のみサインインしてください。')]},{title:l('Your first clip','最初のクリップ'),paragraphs:[l('Copy supported content normally, open ClipsX with its shortcut, search, preview the representations captured, and choose the one to paste.','通常どおり対応コンテンツをコピーし、ショートカットで ClipsX を開き、検索して保存された表現を確認し、貼り付ける形式を選びます。')]}]},
  workflows:{sections:[{title:l('A deliberate pipeline','意図的な流れ'),paragraphs:[l('ClipsX captures canonical content first. Previews, OCR, search data, and extension results are derived so they can be rebuilt without changing the original.','ClipsX はまず原本データを保存します。プレビュー、OCR、検索データ、拡張結果は派生データとして再構築できます。'),l('Pin frequent clips, add notes and tags, filter by source or type, then copy or share the supported representation you need.','頻用クリップをピン留めし、メモやタグ、ソースや種類の絞り込みを使い、必要な対応形式をコピーまたは共有します。')]}]},
  privacy:{sections:[{title:l('Local data boundary','ローカルデータ境界'),paragraphs:[l('Clipboard content, managed files, OCR, full-text indexes, semantic sidecars, provider endpoints, models, credentials, permission grants, and diagnostics remain device-local.','クリップ内容、管理ファイル、OCR、全文インデックス、意味検索データ、接続先、モデル、認証情報、権限、診断情報は端末内に残ります。'),l('ClipsX never silently downloads a model or sends clipboard content to a hosted provider. Any future hosted integration must ask for explicit consent.','モデルを無断でダウンロードしたり、クリップ内容を外部プロバイダーへ送信したりしません。将来の外部連携には明示的な同意が必要です。')]}]},
  'meaning-search':{sections:[{title:l('Optional local retrieval','任意のローカル検索'),paragraphs:[l('Meaning Search adds local embeddings and a derived semantic index. Exact identifiers continue to use lexical search, while semantic results help with concepts and half-remembered phrases.','意味検索はローカル埋め込みと派生インデックスを追加します。正確な識別子は文字検索、概念や曖昧な記憶には意味検索が役立ちます。'),l('You can disable it or delete its index without deleting clips. Changing eligible content schedules a bounded rebuild.','無効化やインデックス削除をしてもクリップは削除されません。対象内容の変更時は制御された再構築が行われます。')]}]},
  ollama:{sections:[{title:l('Connect locally','ローカル接続'),paragraphs:[l('Install and start Ollama separately, then select it in Intelligence. ClipsX accepts loopback endpoints only and reports provider health before indexing.','Ollama を別途導入・起動し、Intelligence で選択します。ClipsX はループバック接続のみ受け付け、インデックス作成前に状態を確認します。'),l('Choose a compatible embedding model yourself. ClipsX does not download models automatically. If health fails, confirm Ollama is running and the selected model exists.','対応する埋め込みモデルを自分で選択します。ClipsX は自動取得しません。接続に失敗した場合は Ollama とモデルを確認してください。')]}]},
  extensions:{sections:[{title:l('Host-owned safety','ホストが管理する安全性'),paragraphs:[l('Extensions run as bounded WASM packages. Signed registry entries describe compatible releases; ClipsX owns capability consent, invocation limits, rendering, accessibility, and quarantine.','拡張機能は制限された WASM として動作します。署名レジストリが互換リリースを示し、権限同意、実行制限、表示、アクセシビリティ、隔離は ClipsX が管理します。'),l('Review permissions after installation and again after a package update changes its checksum. Credentials and grants never sync automatically.','導入時とチェックサムが変わる更新後に権限を確認します。認証情報と許可は自動同期されません。')]}]},
  developers:{sections:[{title:l('Build against the contract','契約に沿って構築'),paragraphs:[l('The desktop repository owns the public extension contract, package CLI, and conformance tests. First-party packages and the signed catalog live in separate repositories.','デスクトップリポジトリが公開拡張契約、パッケージ CLI、適合テストを管理します。公式パッケージと署名カタログは別リポジトリです。'),l('Public hosted APIs are planned, not available. Build current integrations as reviewed extensions rather than depending on an undocumented network API.','公開ホスト API は計画段階です。現時点では未文書化 API に依存せず、審査対象の拡張機能として構築してください。')]}]},
  sync:{sections:[{title:l('What roams','同期されるもの'),paragraphs:[l('Supported profile settings and reviewed extension or command intent can sync between signed-in devices. Local validation and fresh capability consent still apply.','対応プロファイル設定と審査済み拡張・コマンドの選択情報は端末間同期できます。各端末での検証と権限同意は必要です。'),l('Clips, notes, tags, files, archives, credentials, grants, local model endpoints, jobs, diagnostics, and derived data do not sync. Signing out preserves local data.','クリップ、メモ、タグ、ファイル、認証情報、権限、ローカルモデル接続、ジョブ、診断、派生データは同期しません。サインアウトしてもローカルデータは残ります。')]}]},
  platforms:{sections:[{title:l('Release truth','リリース状況'),paragraphs:[l('Windows x64 and Linux x64 are the first desktop release targets. An artifact is advertised only after its platform certification and publishing checks pass.','Windows x64 と Linux x64 が初回デスクトップ対象です。各プラットフォームの検証と公開チェック合格後のみ配布します。'),l('macOS builds are not a primary download until signing, hardened runtime, notarization, and stapling are complete. Linux support targets X11 for the first release.','macOS は署名、Hardened Runtime、公証、ステープル完了まで主要ダウンロードにしません。Linux 初回対応は X11 が対象です。')]}]},
};
